name: oss-release

# Action is schedued to run at 2AM UTC every Wednesday. Executed script ensures release is only generated every other week.
on:
  schedule:
    - cron: '0 2 * * WED'
  workflow_dispatch:

jobs:
  oss-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo # This allows access to the repository's files via the environment variable GITHUB_WORKSPACE
        uses: actions/checkout@v2
      - name: Script to Create OSS Release
        shell: pwsh
        env: # Use secret in repo to make necessary AzureDevOps calls.
          AZUREDEVOPS_PAT: ${{ secrets.AZUREDEVOPS_PAT }}
        run: | # Run powershell script to manage API calls to generate Release.
          Set-Location $env:GITHUB_WORKSPACE\.github\workflows
          .\CreateRelease.ps1
      - name: Upload generated log file
        uses: actions/upload-artifact@v2
        with: # Upload generated log file
          name: log
          path: log.txt
